### ISSUE TITLE
Propose new EDE Code for NXNAME queries

### ISSUE THREAD

**Issue by shuque** [shuque/id-dnssec-compact-lies#4]
For discussion:

Propose new EDE (Extended DNS Error) Code for NXNAME queries, and perhaps more generally for any meta-type that has no defined response behavior. "Invalid Query Type"?

**Comment by chreo** [comment]
I think this is a very useful EDE code, and not just for NXNAME queries but generally. "Invalid Query Type" has my full support

**Comment by shuque** [comment]
Closing issue. The EDE proposal is in the latest version of the draft.
