### ISSUE TITLE
be more explicit about the security implications of no-NXDOMAIN-synthesis

### ISSUE THREAD

**Issue by msinatra** [shuque/id-dnssec-compact-lies#6]
The draft correctly notes in section 5 that compact denial of existence prevents resolvers from doing NXDMAIN synthesis, which means that RFC 8198-style aggressive negative caching is not possible with CDoE.

This has security implications, especially with respect to water torture attacks, if I am not mistaken.  So it might be useful to put some additional explicit text in Section 8, maybe at the end of the second paragraph (or a new third paragraph):

"Additionally, because this method does not allow for aggressive negative caching [RFC8198] among resolvers, it allows for certain types of denial-of-service attacks to be more effective.  This includes so-called Water Torture attacks, where random names are queried, either directly via botnets or across a wide range of public resolver services, in order to intentionally generate non-existence responses from the authoritative servers for a domain.  If the public resolver services cannot synthesize their own NXDOMAIN responses, they must pass all queries on to the domain's authority servers, making resource exhaustion more likely at those latter servers."

You could also just include a citation of some authoritative source that provides a clear definition of Water Torture attacks, rather than relying on my (wordy) embedded definition.

**Comment by shuque** [comment]
Closing. Text incorporated.
